# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    tags:
     - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Update submodules
        run: git submodule update --init

      # Install dependencies
      - name: Install apt-get dependencies
        run: |
          sudo apt-get update
          sudo apt-get install pkg-config libglib2.0-dev libsoup2.4-dev libjson-glib-dev libgee-0.8-dev valac meson
      - name: Build
        run: |
          meson builddir
          ninja -C builddir
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          # Artifact name
          name: output
          # A file, directory or wildcard pattern that describes what to upload
          path: builddir/valapkg
  upload:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: build
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.9
        with:
          # Artifact name
          name: output
          path: output
      - name: Create Release
# You may pin to the exact commit or the version.
# uses: ncipollo/release-action@7c5046364401a3e122086927d07617a3d756b658
        uses: ncipollo/release-action@v1.8.4
        with:
          # An optional set of paths representing artifacts to upload to the release. This may be a single path or a comma delimited list of paths (or globs)
          artifacts: output/valapkg
          # An optional body for the release.
          body: |
            Actions release
            Dependencies (pkg-config names):
            - gobject-2.0
            - glib-2.0
            - gio-2.0
            - libsoup-2.4
            - json-glib-1.0
            - gee-0.8
          # The Github token.
          token: ${{ secrets.GITHUB_TOKEN }}

